name: Update Repository Metrics

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    outputs:
      pr_created: ${{ steps.create_pr.outputs.pr_number }}  # Expose PR number for next job

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Git with Personal Account
        run: |
          git config --global user.name "mohanmanikanta2299"
          git config --global user.email "mohan.manikanta@hashicorp.com"
          git remote set-url origin https://mohanmanikanta2299:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/mohanmanikanta2299/dashboard-metrics.git

      - name: Set Up Environment
        run: |
          echo "Setting up environment variables..."
          echo "REPO_FILE=repos.txt" >> $GITHUB_ENV
          echo "OUTPUT_FILE=metrics.json" >> $GITHUB_ENV

      - name: Install Dependencies
        run: sudo apt-get install -y jq

      - name: Run Metrics Fetch Script
        run: |
          chmod +x scripts/fetch_metrics.sh
          ./scripts/fetch_metrics.sh

        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Check for Changes
        id: check_changes
        run: |
          git diff --quiet metrics.json || echo "CHANGED=true" >> $GITHUB_ENV

      - name: Create Branch and Commit Changes
        if: env.CHANGED == 'true'
        run: |
          BRANCH_NAME="update-metrics-$(date +%Y%m%d%H%M)"
          git checkout -b $BRANCH_NAME
          git add metrics.json
          git commit -m "Update GitHub repository metrics"
          git push origin $BRANCH_NAME
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create Pull Request
        if: env.CHANGED == 'true'
        id: create_pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const { BRANCH_NAME } = process.env;
            const pr = await github.rest.pulls.create({
              owner: "mohanmanikanta2299",
              repo: "dashboard-metrics",
              title: "Automated Update: Repository Metrics",
              head: BRANCH_NAME,
              base: "main",
              body: "This PR updates `metrics.json` with the latest repository metrics.",
              maintainer_can_modify: true
            });
            console.log(`PR Created: ${pr.data.html_url}`);
            core.setOutput("pr_number", pr.data.number);  # Expose PR number

  merge-and-cleanup:
    needs: update-metrics
    runs-on: ubuntu-latest

    if: needs.update-metrics.outputs.pr_created != ''  # Only run if a PR was created

    steps:
      - name: Merge Pull Request and Delete Branch
        uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const owner = "mohanmanikanta2299";
            const repo = "dashboard-metrics";
            const pr_number = "${{ needs.update-metrics.outputs.pr_created }}";

            if (!pr_number) {
              console.log("No PR was created. Skipping merge and cleanup.");
              return;
            }

            // Attempt to merge the PR
            try {
              await github.rest.pulls.merge({
                owner,
                repo,
                pull_number: pr_number,
                merge_method: "squash"
              });
              console.log(`Successfully merged PR #${pr_number}`);
            } catch (error) {
              console.error(`Failed to merge PR #${pr_number}:`, error.message);
              return;
            }
