name: Update Repository Metrics

on:
  schedule:
    - cron: '0 10 * * *'  # Runs every day
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Create GH App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          # required
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false

      - name: Set Up Environment Variables
        run: |
          echo "REPO_FILE=repos.txt" >> $GITHUB_ENV
          echo "OUTPUT_FILE=metrics.json" >> $GITHUB_ENV

      - name: Set Branch Name
        run: echo "branch_name=metrics/update-metrics-$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Check Token Repository Access
        run: |
          curl -s -H "Authorization: Bearer $GITHUB_APP_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/installation/repositories"
        env:
          GITHUB_APP_TOKEN: ${{ steps.app-token.outputs.token }}
  
      - name: Run Metrics Fetch Script
        run: |
          chmod +x scripts/fetch_metrics.sh
          ./scripts/fetch_metrics.sh
        env:
          GITHUB_APP_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Check for Changes
        id: check_changes
        run: |
          if git diff --quiet metrics.json; then
            echo "No changes detected. Skipping PR creation."
            echo "CHANGED=false" >> $GITHUB_ENV
          else
            echo "Changes detected."
            echo "CHANGED=true" >> $GITHUB_ENV
          fi

      - name: Raise a PR and Commit Changes
        if: env.CHANGED == 'true'
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ steps.app-token.outputs.token }}
          branch: ${{ env.branch_name }}
          commit-message: |
            Update Github Metrics
          title: GH Metrics file Update
          delete-branch: true
          body: |
            Hi there 👋

            This PR was auto-generated as part of the daily workflow run which collects the metrics needed for the Dashboard developed by IP Compliance team.
            Please verify the PR and merge the changes if there are no concerns/issues.

            Feel free to run the workflow if there are any concerns with the current data collected in this PR.

            Thank You!